import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { FettuccineGeneratedModule, FettuccineGeneratedSharedModule } from './generated/module.js';
import { FettuccineValidator, registerValidationChecks } from './fettuccine-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type FettuccineAddedServices = {
    validation: {
        FettuccineValidator: FettuccineValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type FettuccineServices = LangiumServices & FettuccineAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const FettuccineModule: Module<FettuccineServices, PartialLangiumServices & FettuccineAddedServices> = {
    validation: {
        FettuccineValidator: () => new FettuccineValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFettuccineServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Fettuccine: FettuccineServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        FettuccineGeneratedSharedModule
    );
    const Fettuccine = inject(
        createDefaultModule({ shared }),
        FettuccineGeneratedModule,
        FettuccineModule
    );
    shared.ServiceRegistry.register(Fettuccine);
    registerValidationChecks(Fettuccine);
    return { shared, Fettuccine };
}
